export const SYMBOLS: Record<string, { code: string; description: string }> = {
  USD: { code: "USD", description: "US Dollar" },
  EUR: { code: "EUR", description: "Euro" },
  GBP: { code: "GBP", description: "British Pound" },
  LKR: { code: "LKR", description: "Sri Lankan Rupee" },
  INR: { code: "INR", description: "Indian Rupee" },
  JPY: { code: "JPY", description: "Japanese Yen" },
  AUD: { code: "AUD", description: "Australian Dollar" },
  CAD: { code: "CAD", description: "Canadian Dollar" },
  CHF: { code: "CHF", description: "Swiss Franc" },
  CNY: { code: "CNY", description: "Chinese Yuan" },
  HKD: { code: "HKD", description: "Hong Kong Dollar" },
  SGD: { code: "SGD", description: "Singapore Dollar" },
  NZD: { code: "NZD", description: "New Zealand Dollar" },
  RUB: { code: "RUB", description: "Russian Ruble" },
  AED: { code: "AED", description: "UAE Dirham" },
  SAR: { code: "SAR", description: "Saudi Riyal" },
  KRW: { code: "KRW", description: "South Korean Won" },
  SEK: { code: "SEK", description: "Swedish Krona" },
  NOK: { code: "NOK", description: "Norwegian Krone" },
  DKK: { code: "DKK", description: "Danish Krone" },
  ZAR: { code: "ZAR", description: "South African Rand" },
  TRY: { code: "TRY", description: "Turkish Lira" },
  THB: { code: "THB", description: "Thai Baht" },
  PKR: { code: "PKR", description: "Pakistani Rupee" },
  BDT: { code: "BDT", description: "Bangladeshi Taka" },
  IDR: { code: "IDR", description: "Indonesian Rupiah" },
  MYR: { code: "MYR", description: "Malaysian Ringgit" },
  PHP: { code: "PHP", description: "Philippine Peso" },
  VND: { code: "VND", description: "Vietnamese Dong" },
  ILS: { code: "ILS", description: "Israeli New Shekel" },
  EGP: { code: "EGP", description: "Egyptian Pound" },
  NGN: { code: "NGN", description: "Nigerian Naira" },
  KES: { code: "KES", description: "Kenyan Shilling" },
  GHS: { code: "GHS", description: "Ghanaian Cedi" },
  UGX: { code: "UGX", description: "Ugandan Shilling" },
  TZS: { code: "TZS", description: "Tanzanian Shilling" },
  MAD: { code: "MAD", description: "Moroccan Dirham" },
  COP: { code: "COP", description: "Colombian Peso" },
  ARS: { code: "ARS", description: "Argentine Peso" },
  BRL: { code: "BRL", description: "Brazilian Real" },
  MXN: { code: "MXN", description: "Mexican Peso" },
  PEN: { code: "PEN", description: "Peruvian Sol" },
  CLP: { code: "CLP", description: "Chilean Peso" },
  PLN: { code: "PLN", description: "Polish Złoty" },
  HUF: { code: "HUF", description: "Hungarian Forint" },
  CZK: { code: "CZK", description: "Czech Koruna" },
  RON: { code: "RON", description: "Romanian Leu" },
  BGN: { code: "BGN", description: "Bulgarian Lev" },
  HRK: { code: "HRK", description: "Croatian Kuna" },
  ISK: { code: "ISK", description: "Icelandic Króna" },
};